## Loader Properties
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.204
neo_version_range=[21.1.0,)
loader_version_range=[4,)
jei_version=19.21.0.247

## Mod Properties
mod_id=pastekluckyblock
mod_name=Pastek's Lucky Block
mod_license=I don't give a fuck
mod_version=1.0.0
mod_group_id=net.pastek.luckyblock
mod_authors=Roi Pasteque
mod_description=A lucky block mod made for compatibility with other mods.