package net.pastek.luckyblock.prefab.configuration;

import net.neoforged.neoforge.common.ModConfigSpec;
import org.apache.commons.lang3.tuple.Pair;

import java.util.List;

public class LBConfigurationHandler {
    public static final ModConfigSpec COMMON_SPEC;
    public static final Common COMMON;

    static {
        final Pair<Common, ModConfigSpec> specPair =
                new ModConfigSpec.Builder().configure(Common::new);
        COMMON_SPEC = specPair.getRight();
        COMMON = specPair.getLeft();
    }

    public static class Common {
        public final ModConfigSpec.IntValue badChance;
        public final ModConfigSpec.IntValue midChance;
        public final ModConfigSpec.IntValue goodChance;
        public final ModConfigSpec.IntValue luckyChance;
        public final ModConfigSpec.ConfigValue<List<? extends String>> lootTables;
        public final ModConfigSpec.BooleanValue debugLogging;
        public final ModConfigSpec.BooleanValue luckyblockTexture;

        public Common(ModConfigSpec.Builder builder) {
            builder.push("pastekluckyblock");

            // ---- Watermelon Texture ----
            luckyblockTexture = builder
                    .comment("If true, the Lucky Block will have a watermelon custom texture.")
                    .define("useWatermelonLuckyBlockTexture", false);

            // ---- Chances Section ----
            badChance = builder
                    .comment(
                            "\nChance out of 100 for BAD loot",
                            "Default: 15"
                    )
                    .defineInRange("badChance", 15, 0, 100);

            midChance = builder
                    .comment(
                            "\nChance out of 100 for MID loot",
                            "Default: 40"
                    )
                    .defineInRange("midChance", 40, 0, 100);

            goodChance = builder
                    .comment(
                            "\nChance out of 100 for GOOD loot",
                            "Default: 40"
                    )
                    .defineInRange("goodChance", 40, 0, 100);

            luckyChance = builder
                    .comment(
                            "\nChance out of 100 for LUCKY loot",
                            "Default: 5"
                    )
                    .defineInRange("luckyChance", 5, 0, 100);

            // ---- Loot Tables Section ----
            lootTables = builder
                    .comment(
                            "\nList of loot table IDs for random chests.",
                            "Accepts both vanilla and modded loot tables.",
                            "Example: \"minecraft:chests/simple_dungeon\""
                    )
                    .defineListAllowEmpty(
                            List.of("lootTables"),
                            () -> List.of(
                                    "minecraft:chests/simple_dungeon",
                                    "minecraft:chests/abandoned_mineshaft",
                                    "minecraft:chests/nether_bridge",
                                    "minecraft:chests/stronghold_library",
                                    "minecraft:chests/stronghold_crossing",
                                    "minecraft:chests/end_city_treasure",
                                    "minecraft:chests/underwater_ruin_big",
                                    "minecraft:chests/underwater_ruin_small",
                                    "minecraft:chests/desert_pyramid",
                                    "minecraft:chests/jungle_temple",
                                    "minecraft:chests/spawn_bonus_chest",

                                    "nova_structures:chests/conduit_ruins/conduit_ruin_big",
                                    "nova_structures:chests/conduit_ruins/conduit_ruin_main",
                                    "nova_structures:chests/conduit_ruins/conduit_ruin_small",
                                    "nova_structures:chests/creeping_crypt/crypt_grave",
                                    "nova_structures:chests/creeping_crypt/crypt_hallway",
                                    "nova_structures:chests/desert_ruins/desert_ruin_grave",
                                    "nova_structures:chests/desert_ruins/desert_ruin_house",
                                    "nova_structures:chests/desert_ruins/desert_ruin_lesser_treasure",
                                    "nova_structures:chests/desert_ruins/desert_ruin_main_temple",
                                    "nova_structures:chests/end_castle/castle_bar",
                                    "nova_structures:chests/end_castle/castle_brewing",
                                    "nova_structures:chests/end_castle/greater_loot",
                                    "nova_structures:chests/end_castle/lesser_loot",
                                    "nova_structures:chests/end_castle/rocket_barrel",
                                    "nova_structures:chests/end_castle/supply",
                                    "nova_structures:chests/end_castle/treasure_lighthouse",
                                    "nova_structures:chests/end_castle/vault_brigattine",
                                    "nova_structures:chests/end_castle/vault_galleon",
                                    "nova_structures:chests/end_castle/vault_slope",
                                    "nova_structures:chests/end_lighthouse/supply_lighthouse",
                                    "nova_structures:chests/end_lighthouse/vault_lighthouse",
                                    "nova_structures:chests/hamlet/hamlet",
                                    "nova_structures:chests/hamlet/hamlet_tresure",
                                    "nova_structures:chests/jungle_ruins/jungle_ruins_main_temple",
                                    "nova_structures:chests/lone_citadel/c_banner",
                                    "nova_structures:chests/lone_citadel/c_cold_barrel",
                                    "nova_structures:chests/lone_citadel/c_dispenser",
                                    "nova_structures:chests/lone_citadel/c_forge",
                                    "nova_structures:chests/lone_citadel/c_forge_chest",
                                    "nova_structures:chests/lone_citadel/c_grave",
                                    "nova_structures:chests/lone_citadel/c_library",
                                    "nova_structures:chests/lone_citadel/c_supply",
                                    "nova_structures:chests/lone_citadel/c_vault",
                                    "nova_structures:chests/lone_citadel/c_vault_boss",
                                    "nova_structures:chests/nether_port/nether_port_chest",
                                    "nova_structures:chests/nether_port/nether_port_supplies",
                                    "nova_structures:chests/nether_skeleton_tower/skeleton_tower_camp",
                                    "nova_structures:chests/nether_skeleton_tower/skeleton_tower_chest",
                                    "nova_structures:chests/nether_skeleton_tower/skeleton_tower_supply",
                                    "nova_structures:chests/piglin_outstation/outstation_generic",
                                    "nova_structures:chests/piglin_outstation/outstation_tower",
                                    "nova_structures:chests/piglin_outstation/outstation_treasure",
                                    "nova_structures:chests/shrine/combat_pot",
                                    "nova_structures:chests/shrine/combat_treasure_1",
                                    "nova_structures:chests/shrine/combat_treasure_2",
                                    "nova_structures:chests/shrine/combat_treasure_3",
                                    "nova_structures:chests/shrine/combat_treasure_4",
                                    "nova_structures:chests/shrine/combat_treasure_5",
                                    "nova_structures:chests/trident_trial_monument/ttm_treasure_chest",
                                    "nova_structures:chests/village/village_birch_house",
                                    "nova_structures:chests/witch_villa/bedroom",
                                    "nova_structures:chests/witch_villa/dirty_clothes",
                                    "nova_structures:chests/witch_villa/gardening",
                                    "nova_structures:chests/witch_villa/general_storage",
                                    "nova_structures:chests/witch_villa/kitchen",
                                    "nova_structures:chests/witch_villa/lab",
                                    "nova_structures:chests/witch_villa/library",
                                    "nova_structures:chests/witch_villa/music_room",
                                    "nova_structures:chests/witch_villa/potion_brewing",
                                    "nova_structures:chests/witch_villa/pumpkin_room",
                                    "nova_structures:chests/witch_villa/slime_room",
                                    "nova_structures:chests/badland_miner_outpost",
                                    "nova_structures:chests/badland_miner_outpost_forge",
                                    "nova_structures:chests/badland_miner_outpost_towers",
                                    "nova_structures:chests/dungeon_1",
                                    "nova_structures:chests/dungeon_2",
                                    "nova_structures:chests/dungeon_3",
                                    "nova_structures:chests/dungeon_4",
                                    "nova_structures:chests/dungeon_5",
                                    "nova_structures:chests/dungeon_6",
                                    "nova_structures:chests/dungeon_7",
                                    "nova_structures:chests/firewatch_tower",
                                    "nova_structures:chests/food_supply",
                                    "nova_structures:chests/illager_camp",
                                    "nova_structures:chests/illager_hideout_brewing",
                                    "nova_structures:chests/illager_hideout_fishing",
                                    "nova_structures:chests/illager_hideout_heart_loot",
                                    "nova_structures:chests/illager_hideout_lesser_treasure",
                                    "nova_structures:chests/illager_hideout_library",
                                    "nova_structures:chests/illager_hideout_meat",
                                    "nova_structures:chests/illager_hideout_random",
                                    "nova_structures:chests/illager_hideout_raw_ores",
                                    "nova_structures:chests/illager_hideout_trash",
                                    "nova_structures:chests/illager_hideout_treasure",
                                    "nova_structures:chests/illager_hideout_utility",
                                    "nova_structures:chests/illager_hideout_vegitarian",
                                    "nova_structures:chests/illager_hideout_weaponry",
                                    "nova_structures:chests/mangrove_witchhud",
                                    "nova_structures:chests/mining_supply",
                                    "nova_structures:chests/pillager_outpost_kitchen",
                                    "nova_structures:chests/pillager_outpost_treasure",
                                    "nova_structures:chests/ruin_loot_master",
                                    "nova_structures:chests/stray_fort_archer",
                                    "nova_structures:chests/stray_fort_loot_generic",
                                    "nova_structures:chests/stray_fort_treasure",
                                    "nova_structures:chests/tavern_quest",
                                    "nova_structures:chests/undead_crypts_grave",
                                    "nova_structures:chests/water_supply",

                                    "kaisyn:village/exclusives/village_wandering_trader_hut",
                                    "kaisyn:village/exclusives/village_piglin_house",
                                    "kaisyn:village/exclusives/village_piglin_barrel",
                                    "kaisyn:village/exclusives/village_mediterranean_house",
                                    "kaisyn:village/exclusives/village_classic_blacksmith",
                                    "kaisyn:village/village_swamp_house",
                                    "kaisyn:village/village_mushroom_house",
                                    "kaisyn:village/village_jungle_house",
                                    "kaisyn:village/village_badlands_house",
                                    "kaisyn:outpost/exclusives/outpost_rustic_barrel",
                                    "kaisyn:outpost/exclusives/outpost_mediterranean_barrel",
                                    "kaisyn:outpost/exclusives/outpost_beach_barrel",
                                    "kaisyn:outpost/common/food",
                                    "kaisyn:outpost/common/armory",

                                    "mvs:abandoned",
                                    "mvs:cart",
                                    "mvs:cartographer_tower",
                                    "mvs:cathedral_base",
                                    "mvs:cathedral_common",
                                    "mvs:cathedral_rare",
                                    "mvs:crystal",
                                    "mvs:empty",
                                    "mvs:floating_islands",
                                    "mvs:general",
                                    "mvs:house_books",
                                    "mvs:house_common",
                                    "mvs:house_desert",
                                    "mvs:house_flower",
                                    "mvs:house_rare",
                                    "mvs:house_uncommon",
                                    "mvs:jungle_tower",
                                    "mvs:large_carts",
                                    "mvs:large_carts_2",
                                    "mvs:mushroom_pond",
                                    "mvs:pillager",
                                    "mvs:rare",
                                    "mvs:swamps",

                                    "aquamirae:chests/frozen_chest",
                                    "aquamirae:chests/maze_camp_chest",
                                    "aquamirae:chests/maze_common_chest",
                                    "aquamirae:chests/ship_1",
                                    "aquamirae:chests/ship_2",

                                    "immersiveengineering:chests/engineers_house",

                                    "perspatium:chests/ice_peak/1",
                                    "perspatium:chests/ice_peak/2",
                                    "perspatium:chests/ice_peak/3",
                                    "perspatium:chests/ice_peak/4",
                                    "perspatium:chests/ice_peak/5",
                                    "perspatium:chests/mercury_fortress/1",
                                    "perspatium:chests/mercury_fortress/2",
                                    "perspatium:chests/mercury_fortress/3",
                                    "perspatium:chests/mirror_temple/1",
                                    "perspatium:chests/mirror_temple/2",
                                    "perspatium:chests/mirror_temple/3",
                                    "perspatium:chests/ruined_space_center/1",
                                    "perspatium:chests/ruined_space_center/2",
                                    "perspatium:chests/stone_fortress/1",
                                    "perspatium:chests/stone_fortress/2",
                                    "perspatium:chests/stone_fortress/3",
                                    "perspatium:chests/stone_fortress/4",
                                    "perspatium:chests/stone_fortress/5",
                                    "perspatium:chests/venera/1",

                                    "whendungeonsarise:chests/ancient_ruins",
                                    "whendungeonsarise:chests/enchanted_chest",

                                    "dungeon_arises:chests/mines_treasure_big",
                                    "dungeon_arises:chests/mines_treasure_medium",
                                    "dungeon_arises:chests/mines_treasure_small",
                                    "dungeon_arises:chests/abandoned_temple/abandoned_temple_entrance",
                                    "dungeon_arises:chests/abandoned_temple/abandoned_temple_map",
                                    "dungeon_arises:chests/abandoned_temple/abandoned_temple_top",
                                    "dungeon_arises:chests/aviary/aviary_barrels",
                                    "dungeon_arises:chests/aviary/aviary_normal",
                                    "dungeon_arises:chests/aviary/aviary_treasure",
                                    "dungeon_arises:chests/bandit_towers/bandit_towers_barrels",
                                    "dungeon_arises:chests/bandit_towers/bandit_towers_gardens",
                                    "dungeon_arises:chests/bandit_towers/bandit_towers_normal",
                                    "dungeon_arises:chests/bandit_towers/bandit_towers_rooms",
                                    "dungeon_arises:chests/bandit_towers/bandit_towers_supply",
                                    "dungeon_arises:chests/bandit_towers/bandit_towers_treasure",
                                    "dungeon_arises:chests/bandit_village/bandit_village_barrels",
                                    "dungeon_arises:chests/bandit_village/bandit_village_normal",
                                    "dungeon_arises:chests/bandit_village/bandit_village_supply",
                                    "dungeon_arises:chests/bandit_village/bandit_village_tents",
                                    "dungeon_arises:chests/bathhouse/bathhouse_barrels",
                                    "dungeon_arises:chests/bathhouse/bathhouse_normal",
                                    "dungeon_arises:chests/ceryneian_hind/ceryneian_hind_treasure",
                                    "dungeon_arises:chests/fishing_hut/fishing_hut_barrels",
                                    "dungeon_arises:chests/foundry/foundry_chains",
                                    "dungeon_arises:chests/foundry/foundry_lava_pit",
                                    "dungeon_arises:chests/foundry/foundry_normal",
                                    "dungeon_arises:chests/foundry/foundry_passage_exterior",
                                    "dungeon_arises:chests/foundry/foundry_passage_normal",
                                    "dungeon_arises:chests/foundry/foundry_treasure",
                                    "dungeon_arises:chests/giant_mushroom/red_giant_mushroom",
                                    "dungeon_arises:chests/giant_mushroom/twin_giant_mushroom",
                                    "dungeon_arises:chests/greenwood_pub/greenwood_pub_barrels_hallways",
                                    "dungeon_arises:chests/greenwood_pub/greenwood_pub_barrels_normal",
                                    "dungeon_arises:chests/greenwood_pub/greenwood_pub_normal",
                                    "dungeon_arises:chests/heavenly_challenger/heavenly_challenger_normal",
                                    "dungeon_arises:chests/heavenly_challenger/heavenly_challenger_supply",
                                    "dungeon_arises:chests/heavenly_challenger/heavenly_challenger_theater",
                                    "dungeon_arises:chests/heavenly_challenger/heavenly_challenger_treasure",
                                    "dungeon_arises:chests/heavenly_conqueror/heavenly_conqueror_barrels",
                                    "dungeon_arises:chests/heavenly_conqueror/heavenly_conqueror_normal",
                                    "dungeon_arises:chests/heavenly_conqueror/heavenly_conqueror_treasure",
                                    "dungeon_arises:chests/heavenly_rider/heavenly_rider_barrels",
                                    "dungeon_arises:chests/heavenly_rider/heavenly_rider_normal",
                                    "dungeon_arises:chests/heavenly_rider/heavenly_rider_treasure",
                                    "dungeon_arises:chests/illager_campsite/illager_campsite_map",
                                    "dungeon_arises:chests/illager_campsite/illager_campsite_supply",
                                    "dungeon_arises:chests/illager_campsite/illager_campsite_tent",
                                    "dungeon_arises:chests/illager_corsair/illager_corsair_barrels",
                                    "dungeon_arises:chests/illager_corsair/illager_corsair_supply",
                                    "dungeon_arises:chests/illager_corsair/illager_corsair_treasure",
                                    "dungeon_arises:chests/illager_fort/illager_fort_barrels",
                                    "dungeon_arises:chests/illager_fort/illager_fort_normal",
                                    "dungeon_arises:chests/illager_fort/illager_fort_treasure",
                                    "dungeon_arises:chests/illager_galley/illager_galley_barrels",
                                    "dungeon_arises:chests/illager_galley/illager_galley_supply",
                                    "dungeon_arises:chests/illager_galley/illager_galley_treasure",
                                    "dungeon_arises:chests/illager_windmill/illager_windmill_barrels",
                                    "dungeon_arises:chests/illager_windmill/illager_windmill_treasure",
                                    "dungeon_arises:chests/infested_temple/infested_temple_room_bookshelf",
                                    "dungeon_arises:chests/infested_temple/infested_temple_room_forge",
                                    "dungeon_arises:chests/infested_temple/infested_temple_room_garden",
                                    "dungeon_arises:chests/infested_temple/infested_temple_room_normal",
                                    "dungeon_arises:chests/infested_temple/infested_temple_room_supply",
                                    "dungeon_arises:chests/infested_temple/infested_temple_room_table",
                                    "dungeon_arises:chests/infested_temple/infested_temple_top_treasure",
                                    "dungeon_arises:chests/jungle_tree_house/jungle_tree_house_barrels",
                                    "dungeon_arises:chests/jungle_tree_house/jungle_tree_house_normal",
                                    "dungeon_arises:chests/jungle_tree_house/jungle_tree_house_treasure",
                                    "dungeon_arises:chests/keep_kayra/keep_kayra_garden_normal",
                                    "dungeon_arises:chests/keep_kayra/keep_kayra_garden_treasure",
                                    "dungeon_arises:chests/keep_kayra/keep_kayra_library_normal",
                                    "dungeon_arises:chests/keep_kayra/keep_kayra_library_treasure",
                                    "dungeon_arises:chests/keep_kayra/keep_kayra_normal",
                                    "dungeon_arises:chests/keep_kayra/keep_kayra_treasure",
                                    "dungeon_arises:chests/lighthouse/lighthouse_top",
                                    "dungeon_arises:chests/mechanical_nest/mechanical_nest_equipment",
                                    "dungeon_arises:chests/mechanical_nest/mechanical_nest_normal",
                                    "dungeon_arises:chests/mechanical_nest/mechanical_nest_supply",
                                    "dungeon_arises:chests/mechanical_nest/mechanical_nest_treasure",
                                    "dungeon_arises:chests/merchant_campsite/merchant_campsite_map",
                                    "dungeon_arises:chests/merchant_campsite/merchant_campsite_supply",
                                    "dungeon_arises:chests/merchant_campsite/merchant_campsite_tent",
                                    "dungeon_arises:chests/mining_system/mining_system_barrels",
                                    "dungeon_arises:chests/mining_system/mining_system_treasure",
                                    "dungeon_arises:chests/monastery/monastery_barrels",
                                    "dungeon_arises:chests/monastery/monastery_bridges",
                                    "dungeon_arises:chests/monastery/monastery_map",
                                    "dungeon_arises:chests/mushroom_house/mushroom_house_barrels",
                                    "dungeon_arises:chests/mushroom_house/mushroom_house_normal",
                                    "dungeon_arises:chests/mushroom_house/mushroom_house_treasure",
                                    "dungeon_arises:chests/mushroom_mines/mushroom_mines_barrels",
                                    "dungeon_arises:chests/mushroom_mines/mushroom_mines_ores",
                                    "dungeon_arises:chests/mushroom_mines/mushroom_mines_tools",
                                    "dungeon_arises:chests/mushroom_mines/mushroom_mines_treasure",
                                    "dungeon_arises:chests/mushroom_village/mushroom_village_barrels",
                                    "dungeon_arises:chests/mushroom_village/mushroom_village_treasure",
                                    "dungeon_arises:chests/plague_asylum/plague_asylum_barrels",
                                    "dungeon_arises:chests/plague_asylum/plague_asylum_cells",
                                    "dungeon_arises:chests/plague_asylum/plague_asylum_normal",
                                    "dungeon_arises:chests/plague_asylum/plague_asylum_potions",
                                    "dungeon_arises:chests/plague_asylum/plague_asylum_storage",
                                    "dungeon_arises:chests/plague_asylum/plague_asylum_treasure",
                                    "dungeon_arises:chests/scorched_mines/scorched_mines_barrels",
                                    "dungeon_arises:chests/scorched_mines/scorched_mines_housing",
                                    "dungeon_arises:chests/scorched_mines/scorched_mines_hub",
                                    "dungeon_arises:chests/scorched_mines/scorched_mines_normal",
                                    "dungeon_arises:chests/scorched_mines/scorched_mines_treasure",
                                    "dungeon_arises:chests/shiraz_palace/shiraz_palace_elite",
                                    "dungeon_arises:chests/shiraz_palace/shiraz_palace_gardens",
                                    "dungeon_arises:chests/shiraz_palace/shiraz_palace_library",
                                    "dungeon_arises:chests/shiraz_palace/shiraz_palace_normal",
                                    "dungeon_arises:chests/shiraz_palace/shiraz_palace_rooms",
                                    "dungeon_arises:chests/shiraz_palace/shiraz_palace_supply",
                                    "dungeon_arises:chests/shiraz_palace/shiraz_palace_towers",
                                    "dungeon_arises:chests/shiraz_palace/shiraz_palace_treasure",
                                    "dungeon_arises:chests/small_blimp/small_blimp_coal_storage",
                                    "dungeon_arises:chests/small_blimp/small_blimp_redstone_chamber",
                                    "dungeon_arises:chests/small_blimp/small_blimp_treasure",
                                    "dungeon_arises:chests/small_prairie_house/small_prairie_house_barrels",
                                    "dungeon_arises:chests/small_prairie_house/small_prairie_house_normal",
                                    "dungeon_arises:chests/small_prairie_house/small_prairie_house_ruined",
                                    "dungeon_arises:chests/thornborn_towers/thornborn_towers_barrels",
                                    "dungeon_arises:chests/thornborn_towers/thornborn_towers_rooms",
                                    "dungeon_arises:chests/thornborn_towers/thornborn_towers_top_rooms",
                                    "dungeon_arises:chests/thornborn_towers/thornborn_towers_top_treasure",
                                    "dungeon_arises:chests/typhon/typhon_treasure",
                                    "dungeon_arises:chests/undead_pirate_ship/undead_pirate_ship_barrels",
                                    "dungeon_arises:chests/undead_pirate_ship/undead_pirate_ship_enchants",
                                    "dungeon_arises:chests/undead_pirate_ship/undead_pirate_ship_supply",
                                    "dungeon_arises:chests/undead_pirate_ship/undead_pirate_ship_treasure",

                                    "dungeons_arise_seven_seas:chests/unicorn_galleon/unicorn_galleon_treasure",
                                    "dungeons_arise_seven_seas:chests/unicorn_galleon/unicorn_galleon_supply",
                                    "dungeons_arise_seven_seas:chests/unicorn_galleon/unicorn_galleon_normal",
                                    "dungeons_arise_seven_seas:chests/unicorn_galleon/unicorn_galleon_barrels",
                                    "dungeons_arise_seven_seas:chests/small_yacht/small_yacht_treasure",
                                    "dungeons_arise_seven_seas:chests/small_yacht/small_yacht_normal",
                                    "dungeons_arise_seven_seas:chests/small_yacht/small_yacht_barrels",
                                    "dungeons_arise_seven_seas:chests/pirate_junk/pirate_junk_treasure",
                                    "dungeons_arise_seven_seas:chests/pirate_junk/pirate_junk_supply",
                                    "dungeons_arise_seven_seas:chests/pirate_junk/pirate_junk_normal",
                                    "dungeons_arise_seven_seas:chests/pirate_junk/pirate_junk_barrels",
                                    "dungeons_arise_seven_seas:chests/victory_frigate/victory_frigate_treasure",
                                    "dungeons_arise_seven_seas:chests/victory_frigate/victory_frigate_supply",
                                    "dungeons_arise_seven_seas:chests/victory_frigate/victory_frigate_normal_upper",
                                    "dungeons_arise_seven_seas:chests/victory_frigate/victory_frigate_normal_lower",
                                    "dungeons_arise_seven_seas:chests/victory_frigate/victory_frigate_barrels",

                                    "repurposed_structures:chests/ancient_cities/end",
                                    "repurposed_structures:chests/ancient_cities/end_spawner_box",
                                    "repurposed_structures:chests/ancient_cities/nether",
                                    "repurposed_structures:chests/ancient_cities/nether_magma_box",
                                    "repurposed_structures:chests/ancient_cities/ocean",
                                    "repurposed_structures:chests/ancient_cities/ocean_ice_box",
                                    "repurposed_structures:chests/bastions/underground/bridge",
                                    "repurposed_structures:chests/bastions/underground/other",
                                    "repurposed_structures:chests/bastions/underground/skeleton_horse_stable",
                                    "repurposed_structures:chests/bastions/underground/treasure",
                                    "repurposed_structures:chests/cities/nether",
                                    "repurposed_structures:chests/cities/overworld",
                                    "repurposed_structures:chests/dungeons/badlands",
                                    "repurposed_structures:chests/dungeons/dark_forest",
                                    "repurposed_structures:chests/dungeons/deep",
                                    "repurposed_structures:chests/dungeons/desert",
                                    "repurposed_structures:chests/dungeons/icy",
                                    "repurposed_structures:chests/dungeons/jungle",
                                    "repurposed_structures:chests/dungeons/mushroom",
                                    "repurposed_structures:chests/dungeons/nether",
                                    "repurposed_structures:chests/dungeons/ocean",
                                    "repurposed_structures:chests/dungeons/snow",
                                    "repurposed_structures:chests/dungeons/swamp",
                                    "repurposed_structures:chests/fortresses/jungle_center",
                                    "repurposed_structures:chests/fortresses/jungle_hallway",
                                    "repurposed_structures:chests/fortresses/jungle_shrine",
                                    "repurposed_structures:chests/igloos/grassy",
                                    "repurposed_structures:chests/igloos/mangrove",
                                    "repurposed_structures:chests/igloos/mushroom",
                                    "repurposed_structures:chests/igloos/stone",
                                    "repurposed_structures:chests/mansions/birch",
                                    "repurposed_structures:chests/mansions/birch_storage",
                                    "repurposed_structures:chests/mansions/desert",
                                    "repurposed_structures:chests/mansions/desert_storage",
                                    "repurposed_structures:chests/mansions/jungle",
                                    "repurposed_structures:chests/mansions/jungle_storage",
                                    "repurposed_structures:chests/mansions/mangrove",
                                    "repurposed_structures:chests/mansions/mangrove_storage",
                                    "repurposed_structures:chests/mansions/oak",
                                    "repurposed_structures:chests/mansions/oak_storage",
                                    "repurposed_structures:chests/mansions/savanna",
                                    "repurposed_structures:chests/mansions/savanna_storage",
                                    "repurposed_structures:chests/mansions/snowy",
                                    "repurposed_structures:chests/mansions/snowy_storage",
                                    "repurposed_structures:chests/mansions/taiga",
                                    "repurposed_structures:chests/mansions/taiga_storage",
                                    "repurposed_structures:chests/mineshafts/birch",
                                    "repurposed_structures:chests/mineshafts/crimson",
                                    "repurposed_structures:chests/mineshafts/dark_forest",
                                    "repurposed_structures:chests/mineshafts/desert",
                                    "repurposed_structures:chests/mineshafts/end",
                                    "repurposed_structures:chests/mineshafts/icy",
                                    "repurposed_structures:chests/mineshafts/jungle",
                                    "repurposed_structures:chests/mineshafts/nether",
                                    "repurposed_structures:chests/mineshafts/ocean",
                                    "repurposed_structures:chests/mineshafts/savanna",
                                    "repurposed_structures:chests/mineshafts/stone",
                                    "repurposed_structures:chests/mineshafts/swamp",
                                    "repurposed_structures:chests/mineshafts/taiga",
                                    "repurposed_structures:chests/mineshafts/warped",
                                    "repurposed_structures:chests/monuments/desert",
                                    "repurposed_structures:chests/monuments/icy",
                                    "repurposed_structures:chests/monuments/jungle",
                                    "repurposed_structures:chests/monuments/nether",
                                    "repurposed_structures:chests/outposts/badlands",
                                    "repurposed_structures:chests/outposts/birch",
                                    "repurposed_structures:chests/outposts/crimson",
                                    "repurposed_structures:chests/outposts/desert",
                                    "repurposed_structures:chests/outposts/giant_tree_taiga",
                                    "repurposed_structures:chests/outposts/icy",
                                    "repurposed_structures:chests/outposts/jungle",
                                    "repurposed_structures:chests/outposts/mangrove",
                                    "repurposed_structures:chests/outposts/nether_brick",
                                    "repurposed_structures:chests/outposts/oak",
                                    "repurposed_structures:chests/outposts/snowy",
                                    "repurposed_structures:chests/outposts/taiga",
                                    "repurposed_structures:chests/outposts/warped",
                                    "repurposed_structures:chests/pyramids/dark_forest",
                                    "repurposed_structures:chests/pyramids/end",
                                    "repurposed_structures:chests/pyramids/flower_forest",
                                    "repurposed_structures:chests/pyramids/giant_tree_taiga",
                                    "repurposed_structures:chests/pyramids/icy",
                                    "repurposed_structures:chests/pyramids/jungle",
                                    "repurposed_structures:chests/pyramids/mushroom",
                                    "repurposed_structures:chests/pyramids/snowy",
                                    "repurposed_structures:chests/ruined_portals/end/large_portal",
                                    "repurposed_structures:chests/ruined_portals/end/small_portal",
                                    "repurposed_structures:chests/ruins/nether",
                                    "repurposed_structures:chests/ruins/land_cold/large",
                                    "repurposed_structures:chests/ruins/land_cold/small",
                                    "repurposed_structures:chests/ruins/land_hot/large",
                                    "repurposed_structures:chests/ruins/land_hot/small",
                                    "repurposed_structures:chests/ruins/land_icy/large",
                                    "repurposed_structures:chests/ruins/land_icy/small",
                                    "repurposed_structures:chests/ruins/land_warm/large",
                                    "repurposed_structures:chests/ruins/land_warm/small",
                                    "repurposed_structures:chests/shipwrecks/crimson/map",
                                    "repurposed_structures:chests/shipwrecks/crimson/supply",
                                    "repurposed_structures:chests/shipwrecks/crimson/treasure",
                                    "repurposed_structures:chests/shipwrecks/end/map",
                                    "repurposed_structures:chests/shipwrecks/end/supply",
                                    "repurposed_structures:chests/shipwrecks/end/treasure",
                                    "repurposed_structures:chests/shipwrecks/nether_bricks/treasure",
                                    "repurposed_structures:chests/shipwrecks/warped/map",
                                    "repurposed_structures:chests/shipwrecks/warped/supply",
                                    "repurposed_structures:chests/shipwrecks/warped/treasure",
                                    "repurposed_structures:chests/strongholds/nether_hallway",
                                    "repurposed_structures:chests/strongholds/nether_library",
                                    "repurposed_structures:chests/strongholds/nether_storage_room",
                                    "repurposed_structures:chests/temples/basalt",
                                    "repurposed_structures:chests/temples/crimson",
                                    "repurposed_structures:chests/temples/ocean",
                                    "repurposed_structures:chests/temples/soul",
                                    "repurposed_structures:chests/temples/taiga",
                                    "repurposed_structures:chests/temples/warped",
                                    "repurposed_structures:chests/temples/wasteland",
                                    "repurposed_structures:chests/villages/badlands_house",
                                    "repurposed_structures:chests/villages/bamboo_house",
                                    "repurposed_structures:chests/villages/birch_house",
                                    "repurposed_structures:chests/villages/cherry_house",
                                    "repurposed_structures:chests/villages/crimson_cartographer",
                                    "repurposed_structures:chests/villages/crimson_fisher",
                                    "repurposed_structures:chests/villages/crimson_house",
                                    "repurposed_structures:chests/villages/crimson_tannery",
                                    "repurposed_structures:chests/villages/crimson_weaponsmith",
                                    "repurposed_structures:chests/villages/dark_forest_house",
                                    "repurposed_structures:chests/villages/giant_taiga_house",
                                    "repurposed_structures:chests/villages/jungle_house",
                                    "repurposed_structures:chests/villages/mountains_house",
                                    "repurposed_structures:chests/villages/mushroom_house",
                                    "repurposed_structures:chests/villages/oak_house",
                                    "repurposed_structures:chests/villages/ocean_cartographer",
                                    "repurposed_structures:chests/villages/ocean_house",
                                    "repurposed_structures:chests/villages/swamp_house",
                                    "repurposed_structures:chests/villages/warped_cartographer",
                                    "repurposed_structures:chests/villages/warped_fisher",
                                    "repurposed_structures:chests/villages/warped_house",
                                    "repurposed_structures:chests/villages/warped_tannery",
                                    "repurposed_structures:chests/villages/warped_weaponsmith"
                            ),
                            obj -> obj instanceof String
                    );

            debugLogging = builder
                    .comment(
                            "\n\n\nEnable detailed debug logs for Pastek Lucky Block loot injections.",
                            "This will show which tables are injected, missing items and other errors.",
                            "Default: false"
                    )
                    .define("debugLogging", false);

            builder.pop();
        }
    }
}
