modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"

[[mods]] #mandatory
modId="pastekluckyblock" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
authors="${mod_authors}" #optional
description='''${mod_description}'''
logoFile="pastek.png"
displayURL="https://github.com/roipasteque/PastekLuckyBlock/tree/1.21.1"

[[dependencies.pastekluckyblock]] # must match the modId in the mods table
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.pastekluckyblock]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"